#!/bin/sh
# Railway / Docker entrypoint for OpenFang.
#
# Responsibilities:
#   1. Resolve the listen address from OPENFANG_LISTEN or Railway-injected PORT.
#   2. Bootstrap a minimal config.toml if none exists (first-boot on a fresh volume).
#   3. Ensure data directories exist.
#   4. Export OPENFANG_LISTEN so the kernel picks it up even if config.toml pre-exists.
#   5. Exec the daemon â€” PID 1 receives signals correctly.
set -e

# â”€â”€ 1. Resolve listen address â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# OPENFANG_LISTEN wins if already set by the user.
# Otherwise derive from Railway-provided PORT, falling back to 4200.
LISTEN="${OPENFANG_LISTEN:-0.0.0.0:${PORT:-4200}}"
export OPENFANG_LISTEN="${LISTEN}"

# â”€â”€ 2. Ensure home / data directories exist â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# HOME is set to /data in the Dockerfile so dirs::home_dir() returns /data.
# Config lives at /data/.openfang/config.toml â€” on the mounted Railway volume.
OPENFANG_DIR="${HOME:-/data}/.openfang"
mkdir -p "${OPENFANG_DIR}/data"
mkdir -p "${OPENFANG_DIR}/agents"
mkdir -p "${OPENFANG_DIR}/skills"

# â”€â”€ 3. Bootstrap config.toml on first boot â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
CONFIG="${OPENFANG_DIR}/config.toml"
if [ ! -f "${CONFIG}" ]; then
  echo "[entrypoint] No config.toml found â€” writing bootstrap config to ${CONFIG}"
  cat > "${CONFIG}" <<TOML
# OpenFang bootstrap config â€” auto-generated by docker-entrypoint.sh
# Edit via Railway Variables (preferred) or by shelling into the container.
#
# api_listen is overridden at runtime by the OPENFANG_LISTEN environment variable.
api_listen = "${LISTEN}"

[default_model]
# Set your preferred provider and model. The API key is read from the env var below.
# Supported providers: anthropic, openai, groq, gemini, deepseek, openrouter, together, mistral, fireworks
provider = "groq"
model = "llama-3.3-70b-versatile"
api_key_env = "GROQ_API_KEY"

[memory]
decay_rate = 0.05
TOML
  echo "[entrypoint] Bootstrap config written."
fi

# â”€â”€ 4. Copy bundled agents into the volume if the agents dir is empty â”€â”€â”€â”€â”€â”€â”€â”€â”€
AGENTS_SRC="/opt/openfang/agents"
AGENTS_DST="${OPENFANG_DIR}/agents"
if [ -d "${AGENTS_SRC}" ] && [ -z "$(ls -A "${AGENTS_DST}" 2>/dev/null)" ]; then
  echo "[entrypoint] Seeding bundled agents into ${AGENTS_DST}"
  cp -r "${AGENTS_SRC}/." "${AGENTS_DST}/"
fi

echo "[entrypoint] Starting OpenFang â€” listening on ${LISTEN}"
exec openfang start
